import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ZabanVerve",
  description: "Generated by Verve Dev Lab",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="bg-light w-screen min-h-screen">{children}</body>
    </html>
  );
}
