version: '1.0'

services:
  postgres: 
    image: postgres:latest 
    ports: 
      - "5431:5432"
    volumes:
      - pg-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=vervez
volumes:
  pg-volume: